# Generated by Django 4.2 on 2025-03-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_number', models.CharField(max_length=50, unique=True, verbose_name='贷款档案编号')),
                ('customer_name', models.CharField(max_length=100, verbose_name='客户姓名')),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='贷款金额')),
                ('loan_date', models.DateField(verbose_name='贷款日期')),
                ('loan_term', models.IntegerField(verbose_name='贷款期限(月)')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('approved', '已批准'), ('rejected', '已拒绝'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='状态')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '贷款档案',
                'verbose_name_plural': '贷款档案',
                'ordering': ['-created_at'],
            },
        ),
    ]
