# Generated by Django 4.2 on 2025-03-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrecord',
            name='id_number',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='身份证号'),
        ),
    ]
