# Generated by Django 4.2 on 2025-03-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_loanrecord_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrecord',
            name='change_history',
            field=models.TextField(blank=True, null=True, verbose_name='溯源记录'),
        ),
        migrations.AddField(
            model_name='loanrecord',
            name='loan_type',
            field=models.CharField(choices=[('personal', '个人贷款'), ('business', '企业贷款'), ('mortgage', '房贷'), ('car', '车贷'), ('other', '其他')], default='personal', max_length=20, verbose_name='贷款类型'),
        ),
        migrations.AddField(
            model_name='loanrecord',
            name='year',
            field=models.IntegerField(default=2024, verbose_name='年份'),
        ),
    ]
