# Generated by Django 4.2 on 2025-03-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_loanrecord_change_history_loanrecord_loan_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrecord',
            name='loan_type',
            field=models.CharField(choices=[('convenience', '便民卡'), ('normal', '普通贷款'), ('rural', '惠农e贷'), ('mortgage', '按揭贷款')], default='personal', max_length=20, verbose_name='贷款类型'),
        ),
    ]
